# !/usr/bin/env python3
# python3 clean_thumbs.py - Search current directories and prompted confirmation process to remove @eaDir
# and Thumb.db generated by Synology

import os
import shutil

def confirm_action(action_description):
    while True:
        response = input(f"Are you sure you want to {action_description}? (y/n): ").strip().lower()
        if response == 'y':
            return True
        elif response == 'n':
            return False
        else:
            print("Invalid response. Please enter 'y' or 'n'.")

def search_and_remove_directories(target_dir, dir_name):
    removed_directories = []
    for root, dirs, files in os.walk(target_dir, topdown=False):
        for dir in dirs:
            if dir == dir_name:
                dir_path = os.path.join(root, dir)
                removed_directories.append(dir_path)

    if not removed_directories:
        print(f"No '{dir_name}' directories found.")
        return

    print(f"Found {len(removed_directories)} '{dir_name}' directories:")
    for dir_path in removed_directories:
        print(dir_path)

    if confirm_action(f"remove {len(removed_directories)} '{dir_name}' directories"):
        for dir_path in removed_directories:
            shutil.rmtree(dir_path)
            print(f"Directory '{dir_path}' removed.")

def remove_thumbs_files(target_dir, file_name):
    removed_files = []
    for root, dirs, files in os.walk(target_dir):
        for file in files:
            if file == file_name:
                file_path = os.path.join(root, file)
                removed_files.append(file_path)

    if not removed_files:
        print(f"No '{file_name}' files found.")
        return

    print(f"Found {len(removed_files)} '{file_name}' files:")
    for file_path in removed_files:
        print(file_path)

    if confirm_action(f"remove {len(removed_files)} '{file_name}' files"):
        for file_path in removed_files:
            os.remove(file_path)
            print(f"File '{file_path}' removed.")

if __name__ == "__main__":
    current_dir = os.getcwd()

    # Search for and remove "@eaDir" directories
    print("Searching for '@eaDir' directories...")
    search_and_remove_directories(current_dir, "@eaDir")

    # Remove "Thumbs.db" files
    print("Searching for 'Thumbs.db' files...")
    remove_thumbs_files(current_dir, "Thumbs.db")

